---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  selector:
    app: sample-app-pod-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP